메인페이지 추가
DontBeAfraidAnanda/snipsnip pull request #8
Opened 2024-06-23 17:46 UTC by HyeanWoo

![스크린샷 2024-06-24 오전 2 46 30](https://github.com/DontBeAfraidAnanda/snipsnip/assets/46041638/5e9be873-59c1-4454-ab8a-35f98391e6ae)

2024-06-24 09:43 UTC, yg1110 commented
오호 상당히 빠른시간에 PR을 올리셨군요
자랑스럽습니다 👍 👍

2024-06-25 05:25 UTC, yg1110 commented on web/app/ui/mainLayoutStyle.ts
> +  paddingInline: 48,
패딩 인라인은 뭔가요?

2024-06-25 05:25 UTC, yg1110 commented on web/app/bookmarks/page.tsx
북마크 폴더 하위로 있어서 북마크 기능을 먼저 만드신줄 잠깐 착각했네요
폴더 구조에 대한 화면을 만드셨는데 bookmarks폴더에 넣으신건 의도된걸까요?

2024-06-25 05:25 UTC, yg1110 commented on web/app/bookmarks/page.tsx
> +          { title: "넥스트 배포하기", key: "0-0-0-0", isLeaf: true },
isLeaf는 true/false에 따라 화면에서 어떻게 달라지나요?

2024-06-25 05:25 UTC, yg1110 commented on web/app/bookmarks/page.tsx
> +const treeData: TreeDataNode[] = [
라이브러리에서 사용하는 트리노드 방식과
api에서 보내주는 데이터 포멧이 많이 다른데
생각해 두신게 있을까요?

제가 생각한 흐름은 두개정도인데 각각 문제가 좀 있어보여서
1. 라이브러리 부모 호출후 각각의 자식도 전부 호출에서 children까지 완성된 데이터를 만들고 화면에 뿌린다 -> 성능상 별로고 느려보여서 유저UX적으로 별로일듯 

2. 폴더를 누를때마다 하위 폴더를 부르는 api를 호출한다
성능상으로 좋아보이지만 라이브러리에서 하위에 폴더가 있는지 없는지 폴더 아이콘? 같은걸 바꿔주는 옵션이 있을지?

2024-06-25 05:25 UTC, yg1110 commented on web/app/bookmarks/page.tsx
> +const treeData: TreeDataNode[] = [
2-1. 아니면 자식 폴더가 있을 경우 children: []으로 해둬도 하위 폴더가 있다고 판단해서 아이콘이 변경될까요?
빈배열로 먼저 해두고 나중에 클릭하면 안에 배열을 채우는 식으로?

2024-06-25 05:25 UTC, yg1110 commented on web/app/bookmarks/page.tsx
> +} from "@/app/ui/mainLayoutStyle";
스타일파일 이름이 mainLayoutStyle이라면 나중에 폴더와, 북마크 페이지 모두 mainLayout에 정의해두고 쓰실 생각이신가요?

2024-06-25 05:25 UTC, yg1110 commented on web/app/bookmarks/page.tsx
> +            <Image
이 부분은 이미지로 해두신 이유가 있을까요?
프로토타입 느낌으로 넣으신걸까요?

2024-06-25 05:25 UTC, yg1110 commented on web/app/bookmarks/page.tsx
> +            <Image
https://via.placeholder.com/150
저도 가끔 쓰는데 이걸로 넣어놔도 비슷한 효과 낼 수 있습니다.

2024-06-25 05:26 UTC, yg1110 requested changes
질문 몇개 남겼습니다. 확인해주세요~

2024-06-25 14:15 UTC, HyeanWoo commented on web/app/ui/mainLayoutStyle.ts
> +  paddingInline: 48,
CSS에서 padding-inline은 padding-inline-start 및 padding-inline-end 속성을 동시에 설정하는 단축 속성입니다. 이 속성들은 요소의 인라인 방향으로 패딩을 정의하는 데 사용되며, 이는 작성 모드, 텍스트 방향 및 레이아웃 방향에 따라 다릅니다.

2024-06-25 14:26 UTC, HyeanWoo commented on web/app/bookmarks/page.tsx
넵 일단 라우팅을 위해서 bookmarks폴더로 만들어놨습니다.

2024-06-25 14:31 UTC, HyeanWoo commented on web/app/bookmarks/page.tsx
> +          { title: "넥스트 배포하기", key: "0-0-0-0", isLeaf: true },
비동기적으로 데이터를 가져오는 경우 leaf노드인지를 결정합니다.
`DirectoryTree`에서 loadData속성을 활성화한 경우에 유효한 특성입니다.

연결해봐야겠지만 화면에서 달라지는 것은 없는 것으로 보여집니다.

2024-06-25 14:32 UTC, HyeanWoo commented on web/app/bookmarks/page.tsx
> +const treeData: TreeDataNode[] = [
2번 방식으로 갈 것 같습니다. 해당 UI 컴포넌트에 데이터 관련된 옵션이 많이 있어서 사용해보려고 합니다.

2024-06-25 14:33 UTC, HyeanWoo commented on web/app/bookmarks/page.tsx
> +} from "@/app/ui/mainLayoutStyle";
분리할 예정입니다~!

2024-06-25 14:33 UTC, HyeanWoo commented on web/app/bookmarks/page.tsx
> +            <Image
오 좋네요! 수정하겠습니다.

2024-06-26 13:52 UTC, yg1110 approved these changes

2024-06-26 13:53 UTC, yg1110 approved these changes
고생하셨습니다 👍

2024-06-26 14:58 UTC, merged